### ISSUE TITLE
Support for macOS Mojave and XCode 10

### ISSUE THREAD

**Issue by chausovSurfStudio** [flockoffiles/SwiftySRP#7]
When I build my project I get next errors:

![2018-09-25 20 37 34](https://user-images.githubusercontent.com/8776643/46031946-fcca1e80-c102-11e8-94f6-aa01f6de095b.png)
![2018-09-25 20 37 47](https://user-images.githubusercontent.com/8776643/46031949-ff2c7880-c102-11e8-95b5-5f9eb8b3bb85.png)

There were no such mistakes in the previous version of macOS + XCode 10, they appeared with the transition to the new version macOS.

Searching in the google hasn't given any results. So I tried to find similar errors in other libraries and found next issue: https://github.com/onmyway133/Arcane/issues/4

Then I tried to change the code, such as the next PR: https://github.com/onmyway133/Arcane/pull/5.
And this changes helped me) So I created next PR on SwiftySRP: https://github.com/flockoffiles/SwiftySRP/pull/6

What do you think about it? There is other variant to fix this issue?

**Comment by flockoffiles** [comment]
I merged the pull request, but then it did not build for me with Xcode 10.
So I had to remove LegacyCommonCrypto entirely (all the module maps and references in the pod spec). Now it builds, but I need to verify tomorrow on a non-Mojave MacOS machine.

Could you check if the pod pulled from the master branch builds for you?
(Pull it from the master branch, not from the 2.7 tag - since that is not available yet).
Once we are sure that it builds, I will make a new tag and push the updated podspec as well.

Thanks!

**Comment by chausovSurfStudio** [comment]
Yes, its all goods on Mojave! Build it from last commit in master.
Do you report the result of the test on non-mojave os in this thread, please?)

**Comment by flockoffiles** [comment]
I checked it on High Sierra and Xcode 10. Works for me.
However, in v2.7 building with Xcode 9 won't work any more, so from this point on it's Xcode 10 only.
I have updated the README to reflect this.

**Comment by flockoffiles** [comment]
I have now pushed v2.7 to cocoapods.
