### ISSUE TITLE
Value of type 'SRPData' has no member 'v'

### ISSUE THREAD

**Issue by burakCokyildirim** [flockoffiles/SwiftySRP#8]
I'm getting "Value of type 'SRPData' has no member 'v'" compile error from xcode.
What should I do?

**Comment by flockoffiles** [comment]
Which version of SwiftySRP, and which version of XCode/Swift?

**Comment by burakCokyildirim** [comment]
I'm using SwiftySRP 2.7 with Cocoapods.
Swift version: 4.2
Xcode version: 10.0

My Code:
![image](https://user-images.githubusercontent.com/25784705/49856632-62c06b00-fe01-11e8-8add-659d7f91fa6e.png)

**Comment by flockoffiles** [comment]
Good catch - the README must be updated.

To get the verifier from SRPData you can use srpData.verifier or srpData.wrappedVerifier

You don't need to call serialize() because you already get it as Data.

In case of the wrapped version, you can access the underlying data by using withDecodedData() method of the wrapper.

I will update the README to bring it more up to date.
Thanks very much again for spotting it!

**Comment by flockoffiles** [comment]
You are probably getting a crash because the verifier data cannot be represented as a UTF-8 string.

If you need a string representation of the verifier (e.g. to include it in a JSON object), you can convert it to base64. In fact, if you are using a standard (Swift) JSON encoder, it will do it for you by default if you feed it a piece of Data. Otherwise, just use base64EncodedString(options:) method on the data.
